#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 14 03:29:10 2020

@author: hms
"""
case1 = [9, [[0,1],[0,3],[0,7],[8,1],[3,6],[1,2],[4,7],[7,5]], [[8,5],[6,7],[4,1]]]
case2 = [9, [[8,1],[0,1],[1,2],[0,7],[4,7],[0,3],[7,5],[3,6]], [[4,1],[5,2]]]
case3 = [9, [[0,1],[0,3],[0,7],[8,1],[3,6],[1,2],[4,7],[7,5]], [[4,1],[8,7],[6,5]]]
n, path, order  = case1


def solution(n, path, order):
    graph = {n: [] for n in range(n)}
    for a, b in path :
        graph[a].append(b)
        graph[b].append(a)
    
    visit = []
    stack = [0]
    
      
    while stack :
        node = stack.pop()
        if node in visit : continue
        visit.append(node)
        children = graph[node]
        for i in children :
            graph[i].pop(graph[i].index(node))
        stack.extend(children)
    
    print(graph)
    for a, b in order :
        graph[a].append(b)
    
    inv_graph = {n: [] for n in range(n)}
    for k, v in graph.items() :
        for val in v :
            inv_graph[val] = [k]
    
    
    for _, v in order :
        visit = [v]
        stack = inv_graph[v]
        while stack :
            node = stack.pop()
            if node == v : return False
            if node in visit : continue
            visit.append(node)
            stack.extend(inv_graph[node])
    return True
    
print(solution(n, path, order))



import sys
sys.setrecursionlimit(10**6)

def haveCycle(node, directedGraph, visit):
    if visit[node]: # DFS를 진행한 적이 있는 노드일 경우
        if visit[node] == -1: # DFS가 진행 중인데 현재 DFS를 또 진행하고 있으므로 사이클 존재(DFS 중복)
            return True
        return False # 전에 DFS를 진행했었지만 DFS가 종료된 경우(DFS 중복 아님)
    visit[node] = -1 # 해당 노드에서 DFS 진행 중인 상태로 설정
    for _next in directedGraph[node]:
        if haveCycle(_next, directedGraph, visit): # 사이클이 존재할 경우
            return True
    visit[node] = 1 # 해당 노드 DFS 종료 상태로 설정(DFS 진행 완료 상태로 설정)
    return False # 사이클이 존재하지 않을 경우
'''
def makeDirectedGraph(node, parent, adj, directedGraph):
    for _next in adj[node]:
        if _next != parent: # 방문하지 않은 노드일 경우
            directedGraph[_next].append(node) # 부모-자식 노드 관계가 반대인 방향 그래프 설정
            makeDirectedGraph(_next, node, adj, directedGraph)

def solution(n, path, order):
    adj, directedGraph, visit = [[] for _ in range(n)], [[] for _ in range(n)], [0]*n
    for parent, node in path:
        adj[parent].append(node) # 무방향 그래프 생성
        adj[node].append(parent)
    makeDirectedGraph(0, -1, adj, directedGraph) # 방향 그래프 생성
    for parent, node in order:
        directedGraph[node].append(parent) # 순서에 대해서도 반대 관계로 방향 그래프 설정
    for node in range(n): # 모든 노드를 시작점으로 설정
        if haveCycle(node, directedGraph, visit): # 방향 그래프에 사이클이 있을 경우
            return False # 동굴의 모든 방을 탐험할 수 없음
    return True # 방향 그래프에 사이클이 없을 경우 동굴의 모든 방을 탐험할 수 있음
'''